-- ROTA360 AKADEMİ V13 — production-ready Supabase schema
create extension if not exists "pgcrypto";
do $$ begin create type public.user_role as enum ('coach','student'); exception when duplicate_object then null; end $$;
do $$ begin create type public.task_type as enum ('konu','soru','tekrar','deneme','youtube'); exception when duplicate_object then null; end $$;
do $$ begin create type public.task_priority as enum ('normal','onemli','kritik'); exception when duplicate_object then null; end $$;
create table if not exists public.profiles(id uuid primary key references auth.users(id) on delete cascade,full_name text not null default 'Yeni Kullanıcı',role public.user_role not null default 'student',avatar_url text,created_at timestamptz not null default now());
create table if not exists public.students(id uuid primary key default gen_random_uuid(),profile_id uuid not null unique references public.profiles(id) on delete cascade,school text,grade text,target_exam text,target_department text,weekly_question_target integer not null default 0 check(weekly_question_target>=0),created_at timestamptz not null default now());
create table if not exists public.coach_students(coach_id uuid not null references public.profiles(id) on delete cascade,student_id uuid not null references public.students(id) on delete cascade,created_at timestamptz not null default now(),primary key(coach_id,student_id));
create table if not exists public.programs(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students(id) on delete cascade,week_start date not null,weekly_goal text,daily_question_target integer not null default 0 check(daily_question_target>=0),coach_note text,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now(),unique(student_id,week_start));
create table if not exists public.tasks(id uuid primary key default gen_random_uuid(),program_id uuid not null references public.programs(id) on delete cascade,task_date date not null,type public.task_type not null,subject text not null,topic text,question_count integer not null default 0 check(question_count>=0),duration_minutes integer not null default 0 check(duration_minutes>=0),priority public.task_priority not null default 'normal',student_note text,is_completed boolean not null default false,completed_at timestamptz,created_at timestamptz not null default now());
create table if not exists public.video_assignments(id uuid primary key default gen_random_uuid(),task_id uuid not null unique references public.tasks(id) on delete cascade,youtube_url text not null check(youtube_url ~* '^https?://(www\\.)?(youtube\\.com|youtu\\.be)/'),title text not null,duration_minutes integer not null default 0,created_at timestamptz not null default now());
create table if not exists public.exam_results(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students(id) on delete cascade,exam_type text not null check(exam_type in('TYT','AYT')),exam_name text,exam_date date not null,turkish_correct int not null default 0 check(turkish_correct>=0),turkish_wrong int not null default 0 check(turkish_wrong>=0),turkish_blank int not null default 0 check(turkish_blank>=0),math_correct int not null default 0 check(math_correct>=0),math_wrong int not null default 0 check(math_wrong>=0),math_blank int not null default 0 check(math_blank>=0),science_correct int not null default 0 check(science_correct>=0),science_wrong int not null default 0 check(science_wrong>=0),science_blank int not null default 0 check(science_blank>=0),social_correct int not null default 0 check(social_correct>=0),social_wrong int not null default 0 check(social_wrong>=0),social_blank int not null default 0 check(social_blank>=0),ayt_subjects jsonb not null default '{}'::jsonb,notes text,total_net numeric(7,2) not null default 0,created_at timestamptz not null default now());
create table if not exists public.topic_analysis(id uuid primary key default gen_random_uuid(),student_id uuid not null references public.students(id) on delete cascade,subject text not null,topic text not null,wrong_count int not null default 0 check(wrong_count>=0),priority text not null default 'normal',recommendation text,updated_at timestamptz not null default now(),unique(student_id,subject,topic));
create table if not exists public.notifications(id uuid primary key default gen_random_uuid(),profile_id uuid not null references public.profiles(id) on delete cascade,title text not null,body text not null,is_read boolean not null default false,created_at timestamptz not null default now());
create index if not exists idx_cs_student on public.coach_students(student_id);create index if not exists idx_tasks_program_date on public.tasks(program_id,task_date);create index if not exists idx_exams_student_date on public.exam_results(student_id,exam_date desc);create index if not exists idx_notifications_profile on public.notifications(profile_id,created_at desc);
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ declare r public.user_role; begin r:=case when new.raw_user_meta_data->>'role'='coach' then 'coach'::public.user_role else 'student'::public.user_role end; insert into public.profiles(id,full_name,role) values(new.id,coalesce(new.raw_user_meta_data->>'full_name','Yeni Kullanıcı'),r) on conflict(id) do nothing; if r='student' then insert into public.students(profile_id) values(new.id) on conflict(profile_id) do nothing; end if; return new; end; $$;
drop trigger if exists on_auth_user_created on auth.users;create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.student_id_of_user() returns uuid language sql stable security definer set search_path=public as $$ select id from public.students where profile_id=auth.uid() limit 1 $$;
create or replace function public.is_coach_of_student(p_student uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.coach_students where coach_id=auth.uid() and student_id=p_student) $$;
create or replace function public.notify_profile(p uuid,t text,b text) returns void language sql security definer set search_path=public as $$ insert into public.notifications(profile_id,title,body) values(p,t,b) $$;
create or replace function public.notify_task_created() returns trigger language plpgsql security definer set search_path=public as $$ declare pid uuid; begin select s.profile_id into pid from programs p join students s on s.id=p.student_id where p.id=new.program_id; if pid is not null then perform public.notify_profile(pid,'Yeni görev',new.subject||coalesce(' · '||new.topic,'')||' için yeni bir görev eklendi.'); end if; return new; end; $$;
drop trigger if exists task_created_notify on public.tasks;create trigger task_created_notify after insert on public.tasks for each row execute procedure public.notify_task_created();
create or replace function public.notify_task_completed() returns trigger language plpgsql security definer set search_path=public as $$ declare cid uuid;sid uuid;begin if new.is_completed and not old.is_completed then select p.student_id into sid from programs p where p.id=new.program_id; select coach_id into cid from coach_students where student_id=sid limit 1; if cid is not null then perform public.notify_profile(cid,'Görev tamamlandı','Öğrencin bir görevi tamamladı: '||new.subject);end if;end if;return new;end;$$;
drop trigger if exists task_completed_notify on public.tasks;create trigger task_completed_notify after update of is_completed on public.tasks for each row execute procedure public.notify_task_completed();
-- RLS
alter table public.profiles enable row level security;alter table public.students enable row level security;alter table public.coach_students enable row level security;alter table public.programs enable row level security;alter table public.tasks enable row level security;alter table public.video_assignments enable row level security;alter table public.exam_results enable row level security;alter table public.topic_analysis enable row level security;alter table public.notifications enable row level security;
drop policy if exists profiles_self on public.profiles;create policy profiles_self on public.profiles for select using(id=auth.uid());drop policy if exists profiles_update_self on public.profiles;create policy profiles_update_self on public.profiles for update using(id=auth.uid()) with check(id=auth.uid());
drop policy if exists profiles_coach_students on public.profiles;create policy profiles_coach_students on public.profiles for select using(exists(select 1 from public.coach_students cs join public.students s on s.id=cs.student_id where cs.coach_id=auth.uid() and s.profile_id=profiles.id));
drop policy if exists students_self_or_coach on public.students;create policy students_self_or_coach on public.students for select using(profile_id=auth.uid() or public.is_coach_of_student(id));drop policy if exists students_self_update on public.students;create policy students_self_update on public.students for update using(profile_id=auth.uid()) with check(profile_id=auth.uid());
drop policy if exists coach_manage_links on public.coach_students;create policy coach_manage_links on public.coach_students for all using(coach_id=auth.uid()) with check(coach_id=auth.uid());
drop policy if exists programs_student_or_coach on public.programs;create policy programs_student_or_coach on public.programs for select using(student_id=public.student_id_of_user() or public.is_coach_of_student(student_id));drop policy if exists programs_coach_insert on public.programs;create policy programs_coach_insert on public.programs for insert with check(created_by=auth.uid() and public.is_coach_of_student(student_id));drop policy if exists programs_coach_update on public.programs;create policy programs_coach_update on public.programs for update using(created_by=auth.uid() and public.is_coach_of_student(student_id)) with check(created_by=auth.uid());
drop policy if exists tasks_visible on public.tasks;create policy tasks_visible on public.tasks for select using(exists(select 1 from programs p where p.id=program_id and (p.student_id=public.student_id_of_user() or public.is_coach_of_student(p.student_id))));drop policy if exists tasks_student_update on public.tasks;create policy tasks_student_update on public.tasks for update using(exists(select 1 from programs p where p.id=program_id and p.student_id=public.student_id_of_user())) with check(exists(select 1 from programs p where p.id=program_id and p.student_id=public.student_id_of_user()));drop policy if exists tasks_coach_insert on public.tasks;create policy tasks_coach_insert on public.tasks for insert with check(exists(select 1 from programs p where p.id=program_id and public.is_coach_of_student(p.student_id)));drop policy if exists tasks_coach_update on public.tasks;create policy tasks_coach_update on public.tasks for update using(exists(select 1 from programs p where p.id=program_id and public.is_coach_of_student(p.student_id))) with check(exists(select 1 from programs p where p.id=program_id and public.is_coach_of_student(p.student_id)));
drop policy if exists videos_visible on public.video_assignments;create policy videos_visible on public.video_assignments for select using(exists(select 1 from tasks t join programs p on p.id=t.program_id where t.id=task_id and (p.student_id=public.student_id_of_user() or public.is_coach_of_student(p.student_id))));drop policy if exists videos_coach_insert on public.video_assignments;create policy videos_coach_insert on public.video_assignments for insert with check(exists(select 1 from tasks t join programs p on p.id=t.program_id where t.id=task_id and public.is_coach_of_student(p.student_id)));drop policy if exists videos_coach_update on public.video_assignments;create policy videos_coach_update on public.video_assignments for update using(exists(select 1 from tasks t join programs p on p.id=t.program_id where t.id=task_id and public.is_coach_of_student(p.student_id))) with check(true);
drop policy if exists exams_student_or_coach on public.exam_results;create policy exams_student_or_coach on public.exam_results for select using(student_id=public.student_id_of_user() or public.is_coach_of_student(student_id));drop policy if exists exams_student_insert on public.exam_results;create policy exams_student_insert on public.exam_results for insert with check(student_id=public.student_id_of_user() or public.is_coach_of_student(student_id));
drop policy if exists topic_student_or_coach on public.topic_analysis;create policy topic_student_or_coach on public.topic_analysis for select using(student_id=public.student_id_of_user() or public.is_coach_of_student(student_id));drop policy if exists notifications_self on public.notifications;create policy notifications_self on public.notifications for select using(profile_id=auth.uid());drop policy if exists notifications_update_self on public.notifications;create policy notifications_update_self on public.notifications for update using(profile_id=auth.uid()) with check(profile_id=auth.uid());

create or replace function public.calculate_exam_net() returns trigger language plpgsql as $$ declare ayt numeric:=0; r jsonb; begin if new.ayt_subjects is not null then for r in select value from jsonb_each(new.ayt_subjects) loop ayt:=ayt+coalesce((r->>'correct')::numeric,0)-coalesce((r->>'wrong')::numeric,0)/4.0; end loop; end if; new.total_net:=new.turkish_correct-new.turkish_wrong/4.0+new.math_correct-new.math_wrong/4.0+new.science_correct-new.science_wrong/4.0+new.social_correct-new.social_wrong/4.0+ayt; return new; end; $$;
drop trigger if exists exam_net_before_write on public.exam_results; create trigger exam_net_before_write before insert or update on public.exam_results for each row execute procedure public.calculate_exam_net();
