import { createClient } from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js@2/+esm";
import { SUPABASE_URL, SUPABASE_ANON_KEY } from "./config.js";
export const supabase=createClient(SUPABASE_URL,SUPABASE_ANON_KEY);
const fail=e=>{if(e) throw e};
export const girisYap=(email,password)=>supabase.auth.signInWithPassword({email,password});
export const kayitOl=(email,password,fullName,role)=>supabase.auth.signUp({email,password,options:{data:{full_name:fullName,role}}});
export const cikisYap=()=>supabase.auth.signOut();
export const mevcutKullanici=()=>supabase.auth.getUser();
export const profilGetir=async()=>{const {data,error}=await supabase.from('profiles').select('*').eq('id',(await supabase.auth.getUser()).data.user.id).single();fail(error);return data};
export const ogrenciGetir=async(profileId)=>{let q=supabase.from('students').select('*').eq('profile_id',profileId).single();const {data,error}=await q;fail(error);return data};
export const ogrencilerim=async()=>{const {data,error}=await supabase.from('coach_students').select('student_id,students(id,profile_id,school,grade,target_exam,target_department,weekly_question_target,profiles(full_name))').order('created_at',{ascending:false});fail(error);return data||[]};
export const baglantiEkle=async(studentId)=>{const {data,error}=await supabase.from('coach_students').insert({coach_id:(await supabase.auth.getUser()).data.user.id,student_id:studentId}).select().single();fail(error);return data};
export const programOlustur=async(p)=>{const {data,error}=await supabase.from('programs').insert(p).select().single();fail(error);return data};
export const programGuncelle=async(id,p)=>{const {data,error}=await supabase.from('programs').update(p).eq('id',id).select().single();fail(error);return data};
export const programGetir=async(studentId,weekStart)=>{const {data,error}=await supabase.from('programs').select('*,tasks(*,video_assignments(*))').eq('student_id',studentId).eq('week_start',weekStart).maybeSingle();fail(error);return data};
export const programlarGetir=async(studentId)=>{const {data,error}=await supabase.from('programs').select('*,tasks(*,video_assignments(*))').eq('student_id',studentId).order('week_start',{ascending:false});fail(error);return data||[]};
export const gorevOlustur=async(t)=>{const {data,error}=await supabase.from('tasks').insert(t).select().single();fail(error);return data};
export const gorevGuncelle=async(id,p)=>{const {data,error}=await supabase.from('tasks').update(p).eq('id',id).select().single();fail(error);return data};
export const goreviTamamla=async(id,completed=true)=>gorevGuncelle(id,{is_completed:completed,completed_at:completed?new Date().toISOString():null});
export const videoAta=async(v)=>{const {data,error}=await supabase.from('video_assignments').upsert(v,{onConflict:'task_id'}).select().single();fail(error);return data};
export const denemeKaydet=async(exam)=>{const {data,error}=await supabase.from('exam_results').insert(exam).select().single();fail(error);return data};
export const denemeleriGetir=async(studentId)=>{const {data,error}=await supabase.from('exam_results').select('*').eq('student_id',studentId).order('exam_date',{ascending:false});fail(error);return data||[]};
export const konularGetir=async(studentId)=>{const {data,error}=await supabase.from('topic_analysis').select('*').eq('student_id',studentId).order('wrong_count',{ascending:false});fail(error);return data||[]};
export const bildirimlerGetir=async()=>{const {data,error}=await supabase.from('notifications').select('*').order('created_at',{ascending:false}).limit(50);fail(error);return data||[]};
export const bildirimOku=async(id)=>{const {error}=await supabase.from('notifications').update({is_read:true}).eq('id',id);fail(error)};
export const profilGuncelle=async(id,p)=>{const {data,error}=await supabase.from('profiles').update(p).eq('id',id).select().single();fail(error);return data};
